#!/usr/bin/env python3
"""Build the glossary (M8 §1–7) from content/glossary.json.

    python3 scripts/build_glossary.py

Writes
  football/js/glossary.js   window.FB_GLOSSARY — the compact data the inline popovers read (term, full, short, analyst,
                            used, tools); build_research.py also reads its keys to validate {term|label} markup
  football/glossary.html    the full, static glossary page: categories, search (synonyms included), plain + technical
                            definitions, why we use it, an example from the research, and "used in" links

The build fails on a missing field or an unknown category / study / tool / methodology section. Synonyms shared by
several terms (e.g. "similarity") are allowed — search is a substring match — and listed in the build output.
"""
import html
import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fb_chrome  # noqa: E402

SITE = Path(__file__).resolve().parent.parent
FB = SITE / "football"
C = json.loads((SITE / "content/glossary.json").read_text())
META = json.loads((FB / "data/meta.json").read_text())
PATH = "/football/glossary"
STUDY = {1: ("environment", "Environment"), 2: ("home-advantage", "Home advantage"), 3: ("opposition", "Opposition"),
         4: ("similarity", "Similarity"), 5: ("transferability", "Transferability")}
TOOL = {"similarity": ("/football/tools/similarity", "Similarity Explorer"), "transfer": ("/football/tools/transfer", "Transfer Calculator"),
        "live": ("/football/live", "Live tracker"), "case": ("/football/case-studies/manchester-united-2024", "Manchester United 2024")}
METHOD = {"data": "Data", "context": "Context adjustment", "opponents": "Opponent strength", "models": "Statistical models",
          "multiple-testing": "Multiple testing", "similarity": "Similarity method", "transfer": "Transfer model", "validation": "Validation"}
FIELDS = ("term", "full", "cat", "aka", "used", "tools", "method", "short", "plain", "analyst", "why", "example")
esc = html.escape


def fail(msg):
    sys.exit("build_glossary: " + msg)


cats = dict(C["categories"])
T = C["terms"]
alias = {}
for k, g in T.items():
    for f in FIELDS:
        if f not in g or (g[f] in ("", None) and f != "method"):
            fail(f"'{k}' is missing '{f}'")
    if g["cat"] not in cats:
        fail(f"'{k}' has unknown category {g['cat']}")
    if not set(g["used"]) <= set(STUDY):
        fail(f"'{k}' uses unknown study {g['used']}")
    if not set(g["tools"]) <= set(TOOL):
        fail(f"'{k}' uses unknown tool {g['tools']}")
    if g["method"] and g["method"] not in METHOD:
        fail(f"'{k}' points at unknown methodology section {g['method']}")
    for a in g["aka"]:
        alias.setdefault(a.lower(), []).append(k)

# ---------------------------------------------------------------- popover data
pop = {k: {f: g[f] for f in ("term", "full", "short", "analyst", "used", "tools")} for k, g in T.items()}
(FB / "js/glossary.js").write_text(
    "/* Generated by scripts/build_glossary.py from content/glossary.json — do not edit by hand.\n"
    "   Inline popover data: short = plain one-liner, analyst = technical; full entries live on /football/glossary. */\n"
    "window.FB_GLOSSARY = " + json.dumps(pop, ensure_ascii=False, separators=(",", ":")) + ";\n")


# ---------------------------------------------------------------- page
def fold(s):
    import unicodedata
    return "".join(c for c in unicodedata.normalize("NFD", s.lower()) if unicodedata.category(c) != "Mn")


def used_in(g):
    links = [f'<a href="/football/research/{STUDY[n][0]}">Study {n:02d} · {STUDY[n][1]}</a>' for n in g["used"]]
    links += [f'<a href="{TOOL[t][0]}">{TOOL[t][1]}</a>' for t in g["tools"]]
    if g["method"]:
        links.append(f'<a href="/football/methodology#{g["method"]}">Methodology · {METHOD[g["method"]]}</a>')
    return "".join(f"<li>{l}</li>" for l in links)


def entry(k, g):
    text = fold(" ".join([g["term"], g["full"], " ".join(g["aka"]), g["short"], g["plain"]]))
    aka = f'<p class="gentry__aka">Also: {esc(", ".join(g["aka"]))}</p>' if g["aka"] else ""
    return f"""<article class="gentry" id="{k}" data-cat="{g["cat"]}" data-text="{esc(text)}" aria-labelledby="{k}-h">
  <header><h3 id="{k}-h">{esc(g["term"])}{f' <span class="gentry__full">{esc(g["full"])}</span>' if g["full"] != g["term"] else ""}</h3>
    <span class="label cat">{esc(cats[g["cat"]])}</span>{aka}</header>
  <p class="gentry__short">{esc(g["short"])}</p>
  <dl>
    <div><dt>Simple</dt><dd>{esc(g["plain"])}</dd></div>
    <div><dt>Technical</dt><dd>{esc(g["analyst"])}</dd></div>
    <div><dt>Why we use it</dt><dd>{esc(g["why"])}</dd></div>
    <div><dt>In the research</dt><dd>{esc(g["example"])}</dd></div>
    <div><dt>Used in</dt><dd><ul class="gentry__used">{used_in(g)}</ul></dd></div>
  </dl>
  <a class="gentry__link" href="#{k}" aria-label="Link to {esc(g["term"])}">#</a>
</article>"""


order = [c for c, _ in C["categories"]]
groups = "".join(
    f'<section class="ggroup" data-group="{c}" aria-labelledby="g-{c}"><h2 id="g-{c}" class="h2-sm">{esc(cats[c])}</h2>'
    + "".join(entry(k, g) for k, g in T.items() if g["cat"] == c) + "</section>" for c in order)
chips = '<button type="button" data-c="" aria-pressed="true">All</button>' + "".join(
    f'<button type="button" data-c="{c}" aria-pressed="false">{esc(cats[c])} <span>{sum(g["cat"] == c for g in T.values())}</span></button>' for c in order)

body = f"""<main id="main" class="gl">
<nav class="crumbs wrap" aria-label="Breadcrumb"><ol><li><a href="/football">Home</a></li><li aria-current="page">Glossary</li></ol></nav>
<header class="gl-hero wrap">
  <p class="lv-kicker">Glossary · {len(T)} terms</p>
  <h1>Football, translated.</h1>
  <p class="lede">The metrics, statistical concepts and modelling terms used throughout the research — explained without assuming you already know the jargon.</p>
  <div class="gl-search">
    <label class="sr-only" for="gq">Search the glossary</label>
    <input class="input" id="gq" type="search" placeholder="Search xG, MAE, PPML…" autocomplete="off" />
    <p class="gl-count" id="gcount" aria-live="polite">{len(T)} terms</p>
  </div>
  <div class="seg gl-cats" id="gcats" role="group" aria-label="Category">{chips}</div>
  <p class="small muted">Every entry has a simple and a technical definition. Technical definitions use the research's own methods — where a term has a more specific meaning here than in a textbook, the research's meaning wins. <a href="/football/methodology">How the research works →</a></p>
</header>
<div class="wrap gl-list" id="glist">{groups}</div>
<p class="wrap gl-empty" id="gempty" hidden>No terms match. Try “xG”, “prediction error” or “similarity”.</p>
</main>

<script>
// Glossary search + category filter over the static entries (synonyms are in each entry's data-text).
document.addEventListener("DOMContentLoaded", function () {{
  "use strict";
  var FB = window.FB, list = document.getElementById("glist"), q = document.getElementById("gq"), cat = "";
  var all = FB.$$(".gentry", list), total = all.length;
  function filter() {{
    var f = FB.fold(q.value.trim()), n = 0;
    all.forEach(function (el) {{
      var ok = (!cat || el.getAttribute("data-cat") === cat) && (!f || el.getAttribute("data-text").indexOf(f) >= 0);
      el.hidden = !ok; if (ok) n++;
    }});
    FB.$$(".ggroup", list).forEach(function (s) {{ s.hidden = !s.querySelector(".gentry:not([hidden])"); }});
    document.getElementById("gcount").textContent = n === total ? total + " terms" : n + " of " + total + " terms";
    document.getElementById("gempty").hidden = n > 0;
  }}
  var t; q.addEventListener("input", function () {{ clearTimeout(t); t = setTimeout(function () {{ filter(); }}, 120); }});
  document.getElementById("gcats").addEventListener("click", function (e) {{
    var b = e.target.closest("button[data-c]"); if (!b) return;
    cat = b.getAttribute("data-c");
    FB.$$("#gcats button").forEach(function (x) {{ x.setAttribute("aria-pressed", x === b ? "true" : "false"); }});
    filter();
  }});
  function goHash(e) {{
    var id = decodeURIComponent(location.hash.slice(1)), el = id && document.getElementById(id);
    if (!el || !el.classList.contains("gentry")) return;
    if (el.hidden) {{ q.value = ""; cat = ""; FB.$$("#gcats button").forEach(function (x) {{ x.setAttribute("aria-pressed", x.getAttribute("data-c") === "" ? "true" : "false"); }}); filter(); }}
    var go = function (smooth) {{ window.scrollTo({{ top: el.getBoundingClientRect().top + window.scrollY - 84, behavior: smooth && !FB.reduce ? "smooth" : "instant" }}); }};
    go(!!e);
    if (!e && document.fonts && document.fonts.ready) document.fonts.ready.then(function () {{ go(false); }});
    el.classList.add("hl"); setTimeout(function () {{ el.classList.remove("hl"); }}, 2400);
  }}
  window.addEventListener("hashchange", goHash);
  goHash(null);
}});
</script>"""

desc = f"Football, translated: {len(T)} terms — xG, xA, PPML, shrinkage, MAE, AUC, retention and more — each with a simple and a technical definition, why the research uses it, and where."
ld = {"@context": "https://schema.org", "@type": "DefinedTermSet", "name": "Home Turf & Hard Opponents — glossary", "url": fb_chrome.SITE + PATH,
      "description": desc, "hasDefinedTerm": [{"@type": "DefinedTerm", "name": g["term"], "alternateName": g["full"] if g["full"] != g["term"] else None,
                                                 "description": g["short"], "url": f"{fb_chrome.SITE}{PATH}#{k}"} for k, g in T.items()]}
for d in ld["hasDefinedTerm"]:
    if d["alternateName"] is None:
        del d["alternateName"]
updated = datetime.fromisoformat(META["tracker_generated_utc"]).strftime("%b %Y")
doc = (fb_chrome.head(PATH, "Glossary · Football, translated · Home Turf & Hard Opponents", desc, "Football, translated", "glossary.png", ld, "website")
       + "\n<body>\n" + fb_chrome.header(PATH) + "\n\n" + body + "\n\n" + fb_chrome.footer(updated) + "\n</body>\n</html>\n")
(FB / "glossary.html").write_text(doc)
dup = {a: ks for a, ks in alias.items() if len(ks) > 1}
print(f"glossary: {len(T)} terms · page {len(doc) / 1024:.1f} KB · popover data {(FB / 'js/glossary.js').stat().st_size / 1024:.1f} KB"
      + (f" · shared synonyms: {', '.join(f'{a}→{ks}' for a, ks in dup.items())}" if dup else ""))
